import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <h1>Solar Invest</h1>
          <nav>
            <Link href="/">Products</Link>
            <a href="#about">About Us</a>
            <a href="#contact">Contact</a>
            <Link href="/cart">Cart</Link>
          </nav>
        </header>
        {children}
        <footer>
          <p>&copy; 2025 Solar Invest. All Rights Reserved.</p>
          <p>
            <a href="#privacy">Privacy Policy</a>d
            <a href="#terms">Terms of Service</a>
          </p>
        </footer>
      </body>
    </html>
  );
}
